default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

dev:
  <<: *default
  host: 
  port: 3306
  username: root
  password: <%= ENV['PASS'] %>
  database: test
